training:
  batch_size: 8
  learning_rate: 5e-5
  num_epochs: 3
  log_interval: 50
  save_dir: "./checkpoints"
  seed: 42

data:
  dataset_path: "./data/dataset.json"   # JSON file of CoT dataset
  train_split: 0.8                      # 80% training, 20% validation
